### ISSUE TITLE
Not working with Django==3.2.2

### ISSUE THREAD

**Issue by crusat** [raiderrobert/django-multiurl#39]
Hi!

Thanks for package!

Unfortunately, it doesn't work with Django==3.2.2.

**Comment by raiderrobert** [comment]
@crusat sorry to hear that. Do you have any specific error to report?

**Comment by MrP01** [comment]
Hello!

I have the same problem after recently upgrading to 3.2.3.
My specific error message says:

```python
Traceback (most recent call last):
  File "/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/lib/python3.8/site-packages/django/core/handlers/base.py", line 167, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/lib/python3.8/site-packages/django/core/handlers/base.py", line 290, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/lib/python3.8/site-packages/django/urls/resolvers.py", line 558, in resolve
    sub_match = pattern.resolve(new_path)
  File "/lib/python3.8/site-packages/django/urls/resolvers.py", line 558, in resolve
    sub_match = pattern.resolve(new_path)
  File "/lib/python3.8/site-packages/django/urls/resolvers.py", line 573, in resolve
    self._extend_tried(tried, pattern, sub_match.tried)

Exception Type: AttributeError at /en/library/hyginus/de-mvnitionibus-castrorvm/
Exception Value: 'MultiResolverMatch' object has no attribute 'tried'
```

Hope this helps. If there is anything I can do, please let me know!

**Comment by MrP01** [comment]
I've now tried around with different Django versions to check which ones are affected and it seems that the problem starts from `Django >= 3.2.0`. Therefore, I currently reverted back to `3.1.11` for the time being.

**Comment by raiderrobert** [comment]
@MrP01 thanks for the debugging! It'll probably be a couple weeks before I can fix it. So PRs in the meantime are welcome if someone else wants to take a shot!

**Comment by igerko** [comment]
I've created PR (#40) for this issue. Please review it and maybe release after that ?

**Comment by raiderrobert** [comment]
I've ran the tests and verified that it's fixed. So closing the issue. Thanks to @igerko for doing the leg work!
